### ISSUE TITLE
Multiple cancer types

### ISSUE THREAD

**Issue by rg-code** [mksamur/RTCGAToolbox#20]
I was wondering if it is possible to create a FirehoseData object with more than one cancer type, currently the script allows for one cancer type at a time. I will greatly appreciate if you can let me know if changing getFirehoseData.R as follows will work 

`if(!class(dataset)=="character" || is.null(dataset) || nchar(dataset) < 2)`

 and adding a loop to download all the datatypes as required.

Alternatively, I was thinking about just creating a file with all the dataset merged  within working directory and using that file in RTCGAToolbox dataset instead.

**Comment by LiNk-NY** [comment]
Hi @rg-code, 
Unfortunately, there is no active development for this package. 
Using the FirehoseData data structure does not provide much in term of richness of methods. 
I would look for other ways of doing this. 

Your question is important. There should be some structure that combines more than one cancer type. 
If you're just handling one type of data (e.g., expression data), you may possibly create a `MultiAssayExperiment` with 2 elements of the same class (`ExpressionSet`/`SummarizedExperiment`) in the `ExperimentList`, one for each cancer type and include clinical data in the `pData` slot. 

Best regards,
Marcel

**Comment by rg-code** [comment]
@LiNk-NY  Thanks a lot for prompt response. 

I am trying to do survival analysis (OS) using KM plots. Would creating a local datasets containing merged clinical, mutation, RNA-seq and gistic dataset across all the desired cancer type work ?

**Comment by LiNk-NY** [comment]
The MultiAssayExperiment isn't designed to handle multiple cancers. 
This depends on how you want to do your analysis. 

Since you have more than one data type I would recommend creating 2 `MultiAssayExperiment`s (one for each cancer) and trying to run your analyses that way. 

You could also create a `MultiAssayExperiment` for each data type (i.e., 1 Mutation `MultiAssayExperiment` with 2 elements in the `ExperimentList` (1 for each cancer), 1 RNA-seq `MultiAssayExperiment` etc.) and doing analyses that way. 

The other option would be to merge your clinical datasets (from each cancer) and somehow keep track of patients by appending the cancer to the patient ID in the `pData` rows. You could then include all the data in the `ExperimentList` of the `MultiAssayExperiment`. 

But again neither of these options are great for analyzing cross-disease data. The strengths of the MultiAssayExperiment lie in combining different data types for a particular cancer.

**Comment by LiNk-NY** [comment]
Hi Rohit, @rg-code 
We recently published `curatedTCGAData`. A package for downloading TCGA data. 
You can enter multiple cancer and have a merged clinical dataset for analyses. 

See it at: http://bioconductor.org/packages/release/data/experiment/html/curatedTCGAData.html

Regards,
Marcel
