### ISSUE TITLE
GetFirehoseData not working due to github server error

### ISSUE THREAD

**Issue by DavisWeaver** [mksamur/RTCGAToolbox#34]
When running this code- 
"TCGA_Data_all <- getFirehoseData(
      dataset = cancer_type[i],
      miRNASeqGene = TRUE,
      RNASeq2GeneNorm = TRUE,
      clinical = TRUE,
      RNASeqGene = TRUE,
      fileSizeLimit = 3000,
      destdir = "C:/Users/dtw43/Music"
    )"

I get this error: It was working for this exact code as recently as last night. Very weird.
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://raw.githubusercontent.com/mksamur/RawDataURLs/master/fmineRdataset.txt': HTTP status was '500 Internal Server Error'

**Comment by LiNk-NY** [comment]
Hi Davis, @DavisWeaver 
GitHub is having issues currently. Please see: https://www.githubstatus.com/

I will look into porting this file into the package in the near future. 
Thanks!
-Marcel

**Comment by DavisWeaver** [comment]
Thank you! Love the package - it is a lifesaver. By the way - I notice you
said windows OS does not support getFireHoseData - I have actually found
that if you place the dest directory near the root (why mine
is "C:/Users/dtw43/Music" rather than something that makes sense) then it
works fine. All the best,

Davis

**Comment by LiNk-NY** [comment]
Hi Davis, @DavisWeaver 

Yes, because we are downloading files with long file names from the service. Windows has a hard time with really long paths. There has been some discussion surrounding this but no real (user-friendly) programmatic solutions.
Shortening the path by downloading the data into a short file path will give you good results.
I'm glad you're finding the package helpful!

If you'd like easier to use integrated TCGA data, check out `curatedTCGAData` on Bioconductor
as well. 

Best regards,
Marcel
